---
title: "MATH 137: Calculus I Honours (Fall 2020)"
format: html

---


#### University of Waterloo — Fall 2020 
_Section instructor: Mark W. Girard_  

This webpage contains some of the information my students in my sections of MATH 173 at the University of Waterloo in Fall 2020.


### Lecture Notes

Below is an organized list of lecture notes, with corresponding textbook sections.

| Lecture # | Textbook Sections       | Notes |
|-----------|--------------------------|-------|
| 0.5       | 2.1                      | [LectureNotes_2.1.pdf](LectureNotes_2.1.pdf) |
| 1         | 2.9, 2.10               | [LectureNotes_2.9-2.10.pdf](LectureNotes_2.9-2.10.pdf) |
| 2         | 3.1, 3.2                | [LectureNotes_3.1-3.2.pdf](LectureNotes_3.1-3.2.pdf) |
| 3         | 3.3–3.4, 3.7–3.9        | [LectureNotes_3.3_3.4_3.7-3.9.pdf](LectureNotes_3.3_3.4_3.7-3.9.pdf) |
| 4         | 3.5, 3.6, 3.10, 3.11    | [LectureNotes_3.5_3.6_3.10_3.11.pdf](LectureNotes_3.5_3.6_3.10_3.11.pdf) |
| 5         | 3.12, 3.13, 4.2.1       | [LectureNotes_3.12_3.13_4.2.1.pdf](LectureNotes_3.12_3.13_4.2.1.pdf) |
| 6         | 4.2.3–4.2.5             | [LectureNotes_4.2.3-4.2.5.pdf](LectureNotes_4.2.3-4.2.5.pdf) |
| 6.5       | 4.2, 4.3                | [LectureNotes_4.2-4.3.pdf](LectureNotes_4.2-4.3.pdf) |
| 7         | 4.2.7                   | [LectureNotes_4.2.7.pdf](LectureNotes_4.2.7.pdf) |
| 8         | 5.1, 5.2                | [LectureNotes_5.pdf](LectureNotes_5.pdf) |


## Solutions to homework assignments

The solutions provided by the course coordinator were not very clear or written very well. To help you improve your proof-writing techniques, I wrote up a collection of nicely written solutions to the homework assignments in a proper way.

You can find the solutions (along with good proof-writing tips) [here](sols.pdf).

## Final Exam Practice

**Note**: These files are intended to provide you help to do some practice to prepare for the final exam for this course, but do not necessarily reflect the specific problems that will appear on your exam.

### Practice problems
I made a collection of practice problems to help you prepare. 

- Here are the [practice problems](MATH137_final_practice_probs.pdf)
- Here are the [solutions](MATH137_final_practice_probs_solutions.pdf) are the solutions.

### Exams from previous terms
Here are some final exams from previous years with solutions.

-  Fall 2018 \[[Exam](137 Final Exam F18.pdf) and [solutions](MATH 137 F18 FE Sols.pdf)\]
- Fall 2019 \[[Exam](F19 Practice Final.pdf) and [solutions](MATH 137 Practice Final Exam Solutions.pdf)\]