project:
  type: website

website:
  title: "Mark W. Girard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Academic"
        href: academic/academic.qmd
      - text: "Puzzles"
        href: riddlers.qmd
      - text: "Blog"
        href: blog/index.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
    css: styles.css
