---
title: "ECE 206 (Fall 2019)"
format: html

---


# Advanced Calculus 2 for Electrical Engineers
University of Waterloo

## Course information

This is the webpage for ECE 206 taught during the 2019 Fall term.

**Syllabus and course schedule**: [Syllabus](sylabus.pdf)

**Instructor**: [Mark Girard](http://markwgirard.github.io) \[email: <m4girard@uwaterloo.ca>\]

**TA**: Zhibing Sun  \[email: <zhibing@uwaterloo.ca>\]

**Time and Location**:

 - Lectures: Tues/Wed/Thurs 15:30-16:20 in E7 4417
 -  Labs/tutorials. Wed 17:30-18:20 in E7 4433
 - Office hours: 9:00-10:00 on Mondays and 12:00-13:00 Wednesdays (or by appointment).

Additional **makeup lectures** are scheduled Thurs 12:30-13:20 in E7 4417 for the following dates:
  
  - Sep 12, Sep 26, Oct 10, Oct 31, Nov 14, Nov 28.


## Course Schedule

| Lecture Notes           | Lecture Dates                       | Tutorial / Quizzes            | Practice Problems                | Solutions                        |
|-------------------------|-------------------------------------|-------------------------------|----------------------------------|----------------------------------|
| [Week 0](NotesWeek00.pdf)       |                                 |                               |                                  |                                  |
| [Week 1](NotesWeek01.pdf)       | September 4 and 5               | (no tutorial)                 | [Problems Week 1](ProblemsWeek01.pdf) | [Solutions](ProblemsWeek01_solutions.pdf) |
| [Week 2](NotesWeek02.pdf)       | September 10–12 (+makeup)       |                               | [Problems Week 2](ProblemsWeek02.pdf) | [Solutions](ProblemsWeek02_solutions.pdf) |
| [Week 3](NotesWeek03.pdf)       | September 17–19                 | Quiz 1                        | [Problems Week 3](ProblemsWeek03.pdf) | [Solutions](ProblemsWeek03_solutions.pdf) |
| [Week 4](NotesWeek04.pdf)       | September 24–26 (+makeup)       | Quiz 2 (Sept 26)              | [Problems Week 4](ProblemsWeek04.pdf) | [Solutions](ProblemsWeek04_solutions.pdf) |
| [Week 5](NotesWeek05.pdf)       | October 1–3                     |                               | [Problems Week 5](ProblemsWeek05.pdf) | [Solutions](ProblemsWeek05_solutions.pdf) |
| [Week 6](NotesWeek06.pdf)       | October 8–10 (+makeup)          | Quiz 3                        | [Problems Week 6](ProblemsWeek06.pdf) | [Solutions](ProblemsWeek06_solutions.pdf) |
| [Week 7](NotesWeek07.pdf)       | Reading week                    | (no tutorial)                 |                                  |                                  |
| [Week 8](NotesWeek08.pdf)       | October 29–31 (+makeup)         | Quiz 4 (Oct 31)               | [Problems Week 8](ProblemsWeek08.pdf) | [Solutions](ProblemsWeek08_solutions.pdf) |
| [Week 9](NotesWeek09.pdf)       | November 5–7                    | Quiz 5                        | [Problems Week 9](ProblemsWeek09.pdf) | [Solutions](ProblemsWeek09_solutions.pdf) |
| [Week 10](NotesWeek10.pdf)      | November 12–14 (+makeup)        | Quiz 6                        | [Problems Week 10](ProblemsWeek10.pdf) | [Solutions](ProblemsWeek10_solutions.pdf) |
| [Week 11](NotesWeek11.pdf)      | November 19–21                  |                               | [Problems Week 11](ProblemsWeek11.pdf) | [Solutions](ProblemsWeek11_solutions.pdf) |
| [Week 12](NotesWeek12.pdf)      | November 26–28 (+makeup)        | ~~Quiz 7~~ (<span style="color: red;">cancelled</span>)           | [Problems Week 12](ProblemsWeek12.pdf) | [Solutions](ProblemsWeek12_solutions.pdf) |


## Quizzes

|                  | Date (location) |       |
|------------------|------|---------------|
| [Quiz 1](Quiz1.pdf) | Sept 18 (in tutorial)| [solutions](Quiz1_solutions.pdf) |
| [Quiz 2](Quiz2.pdf) | Sept 26 (in class)   | [solutions](Quiz2_solutions.pdf) |
| [Quiz 3](Quiz3.pdf) | Oct 9 (in tutorial)  | [solutions](Quiz3_solutions.pdf) |
| [Quiz 4](Quiz4.pdf) | Oct 31 (in tutorial) | [solutions](Quiz4_solutions.pdf) |
| [Quiz 5](Quiz5.pdf) | Nov 5 (in tutorial)  | [solutions](Quiz5_solutions.pdf) |
| [Quiz 6](Quiz6.pdf) | Nov 13 (in tutorial) | [solutions](Quiz6_solutions.pdf) |




## Midterm

The midterm will be on Thursday October 24 at 16:45-19:00 in E7-4417.

The midterm will cover all of the course material up to the end of Week 6. Find a list of topics to study [here](MidStudyGuide.pdf) and the formula sheet that will be available [here](formulasheet.pdf).

You can find a previous midterm to help you study [here](Previous Midterm 2.pdf).

**\*Update\***: Here is the [midterm](Midterm.pdf) and [solutions](midterm_solutions.pdf).


## Final

The final exam will be on Friday, August 19 at 8:00am in room ES 162.

The exam will cover all of the course material.

Here are a few final exams from previous years.

* [Fall 2017 final](2017Exam.pdf) and [solutions](2017ExamSolutions.pdf)
* [Spring 2018 final](2018Exam.pdf) and [solutions](2018ExamSolutions.pdf)

\[**Warning**: Other instructors use different notation/terminology that I do in this course. These exams may not reflect the material that will be covered in this term's final.\]